---
- name: My test playbook
  hosts: all
  become: yes
  tasks: 
  - name: this is to install a package
    yum: 
      name: httpd
      state: present
    notify: starting httpd 
  handlers:
  - name: starting httpd
    service:
      name: httpd      
      state: started

